services:
  - type: web
    name: store-rating-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: store-rating-db
          property: connectionString
      - key: JWT_SECRET
        sync: false

databases:
  - name: store-rating-db
    databaseName: store_rating
    plan: free
